import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link"
import "./globals.css"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="max-w-3xl mx-auto px-6 py-6 flex justify-between items-center">
          {/* Left: Name / Home */}
          <Link href="/" className="font-semibold">
            Eric Criteser
          </Link>

          {/* Right: Navigation */}
          <nav className="flex gap-6 text-sm text-gray-600">
            <Link href="/projects" className="hover:text-black">
              Projects
            </Link>
            <Link href="/about" className="hover:text-black">
              About
            </Link>
            <Link href="/contact" className="hover:text-black">
              Contact
            </Link>
          </nav>
        </header>

        <main>{children}</main>
      </body>
    </html>
  )
}
